language: node_js
node_js:
  - "8"
matrix:
  fast_finish: true

branches:
  only:
  - dev
  - master

notifications:
  slack:
    rooms:
      - $SLACK_TOKEN
    on_pull_requests: false

before_install:
  - yarn install

before_deploy:
  - bash scripts/prepare-deploy.sh

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: dist
  on:
    branch:
    - master
    - dev
