language: node_js
branches:
  only:
  - master
notifications:
  slack:
    rooms:
      - binary-group:TI7oyWjkwf9Xx2Rllt2Pr5zY
    on_pull_requests: false
node_js:
  - "8"
before_script:
  - yarn install
script:
  - yarn gh-pages -- --repo 'git@github.com:regentmarkets/chartiq.git'
